version: "3"
services:
  transformers:
    restart: always
    build: .
    tty: true
    privileged: true
    volumes:
      - ./notebooks:/work/notebooks
      - ./dataset:/work/dataset
      - ./src:/work/src
      - ./model:/work/model
      - ./results:/work/results
      - ./plots:/work/plots
    command: jupyter-lab --allow-root --ip=0.0.0.0 --port=8888 --no-browser --NotebookApp.token='' --notebook-dir=/work
    ports:
      - "8888:8888"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
